title: Kavin M. Govindarajan # your name (or website title) here
logo: "/images/DSC_0117%20(3).JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Park Scholar at North Carolina State University
  <br><br>
  BS Aerospace Engineering | BS Applied Mathematics
  <br><br>
  <a href="https://www.linkedin.com/in/kavin-govindarajan-7b7318179/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
